Fix debounce and sync-obsidian-vault-when-changed
`sync-obsidian-vault-when-changed` uses `watchexec` to watch for changes
in an Obsidian vault. The sync script is wrapped with `debounce`. I have
it so that if changes are made to a file, it will send a `USR1` signal
to `debounce`. `debounce` traps `USR1` to restart a timer rather than
kill the script.

However, I found the script kept dying after file changes. The script
runs a loop and `sleep`s on each iteration. Unfortunately because
`sleep` (or any command) runs is a subshell, it does not inherit the
`USR1` trap, so it dies. And because we are using `set -e` the whole
script dies. So we work around that.

diff --git a/src/bin/debounce b/src/bin/debounce
--- a/src/bin/debounce
+++ b/src/bin/debounce
@@ -16,8 +16,8 @@ print-usage() {
 USAGE: $EXECUTABLE [OPTIONS] -- [COMMAND]
 
 \`$EXECUTABLE\` runs the given command once and then waits for the given number
-of seconds to run the given command again. If it is sent the signal USR1, then it
-starts the timer over again.
+of seconds to run the given command again. If it is sent the signal USR1, then
+it starts the timer over again.
 
 OPTIONS:
 
@@ -100,6 +100,8 @@ main() {
   parse-args "$@"
   validate-args
 
+  trap true SIGUSR1
+
   set +e
   debug "Executing command..."
   "${command[@]}"
@@ -114,18 +116,24 @@ main() {
   time_to_run="$((current_time+duration))"
 
   while true; do
-    trap 'debug "Received SIGUSR1, advancing timer by $duration."; current_time=$(date +%s); trap : USR1; echo "Moving on."' USR1
+    trap 'debug "Received SIGUSR1, advancing timer by $duration."; current_time=$(date +%s)' SIGUSR1
 
     if [[ $current_time -gt $time_to_run || $current_time -eq $time_to_run ]]; then
       debug "Time to run the command!"
+      trap true SIGUSR1
       break
     fi
 
     debug "It's not time to run this command yet, waiting a second..."
+    # We need to disable `set -e` because `sleep 1` does not trap `SIGUSR1`
+    # (since it runs in a subshell) so it will die, causing the whole script to
+    # die. We don't want that to happen so we need to ignore errors.
+    set +e
     sleep 1
+    set -e
 
     current_time=$(date +%s)
-    trap : USR1
+    trap true SIGUSR1
   done
 
   set +e
