Make sync-obsidian-vault-when-changed work on Termux

diff --git a/src/bin/sync-obsidian-vault-when-changed b/src/bin/sync-obsidian-vault-when-changed
--- a/src/bin/sync-obsidian-vault-when-changed
+++ b/src/bin/sync-obsidian-vault-when-changed
@@ -1,8 +1,21 @@
 #!/bin/bash
 
+path_to_watchexec=
+if [[ -e /data/data/com.termux/files/usr/bin/watchexec ]]; then
+  path_to_watchexec=/data/data/com.termux/files/usr/bin/watchexec
+elif [[ -e /opt/homebrew/bin/watchexec ]]; then
+  path_to_watchexec=/opt/homebrew/bin/watchexec
+else
+  echo "ERROR: Could not find watchexec"
+  exit 1
+fi
+
 # This script is designed to be run within a launch agent and therefore
 # Homebrew-installed executables may not be on the PATH.
-/opt/homebrew/bin/watchexec \
+#
+# On macOS, you can get this by running: `brew install watchexec`
+# On Termux, you can get this by running: `pkg install watchexec`
+$path_to_watchexec \
   --watch "$HOME/obsidian-vault" \
   --on-busy-update=restart \
   --debounce 5s \
